theme: jekyll-theme-slate
title: Nehemias Feliz Ferreras
description: Personal website
github:
  is_project_page: true
  repository_url: https://github.com/juniornff/juniornff.github.io
collections:
  posts:
    output: true
    permalink: /posts/:path/
plugins:
  - jekyll-paginate
  - jekyll-sitemap